services:
  ### Symfony + PHP (si tu veux ajouter plus tard)
  # php:
  #   image: php:8.2-fpm
  #   volumes:
  #     - .:/var/www/html
  #   working_dir: /var/www/html
  #   depends_on:
  #     - mercure

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: symfony_mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_ALLOW_ANONYMOUS: 1
      MERCURE_CORS_ALLOWED_ORIGINS: http://127.0.0.1:8000
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  ###< symfony/mercure-bundle ###

volumes:
  mercure_data:
  mercure_config:
