parameters:
    # ici tes paramètres, si tu en as

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false      # par défaut les services sont privés

    # Enregistre tous les services dans src/ sauf les exclus
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Rendre le contrôleur public pour éviter l'erreur
    App\Controller\Api\ChatController:
        public: true
